build:
  lint-and-test:
    image: quay.io/buildo/node5-npm3
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
    commands:
      - npm i
      - npm run lint
      - npm test

cache:
  mount:
    - /drone/.npm
