build:
  lint-and-test:
    image: node:5
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      - npm i
      - npm run lint
      - npm test

  generate-readme:
    image: node:5
    commands:
      - git remote set-url origin git@github.com:buildo/react-flexview.git
      - npm run generate-readme
      - git add src/README.md
      - if ! git diff-index --quiet HEAD -- src/README.md; then
          git config --global user.name "nemobot";
          git config --global user.email "our-bots@buildo.io";
          git commit -m "Update README [skip CI]";
          git push origin master;
        fi
    when:
      branch: master

cache:
  mount:
    - /drone/.npm
