build:
  test:
    image: node:8
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      - npm i
      - npm run typecheck
      - npm test

cache:
  mount:
    - /drone/.npm
